### PR TITLE
Added user creation, user deletion, user info editing, and user info …

### PR DESCRIPTION
**Pull request by noahismith**
…viewing

### CODE REVIEW

**Review by exponentialbit1024 — COMMENTED** [review]
-the create user isn't going to be a route, it will just be a method called from the auth
-asserting is a bad way of authenticating, if there's a better way I'd go for it, if not and this works, we can roll with it for now
- also you don't have to authenticate from the DB for every request, that's the whole point of implementing our own JWT, I will be writing those methods sometime this week, so you can use them for userBp

**Comment by noahismith** [comment]
- I wrote the create user route, to help me test the other methods. I can remove it now though if need be.
- Also I'm confused on what you mean by "asserting is a bad way of authenticating" are you refering to the assert statemnts in models.py or something else? Either way, do you have any suggestions that I can look into?
- I think instead of "# Authenticate" in each DB request, I should have wrote something like "# Verify token via method call" Does that clarify or do I need to make more changes?

**Comment by exponentialbit1024** [comment]
so instead of just assert do an if and return true or false instead of returning the assert.
- for the authenticate, you're still calling the validate method, which doesn't need to be there, that wrapper has to be around the JWT check

**Review by exponentialbit1024 — APPROVED** [review]
alright this is going in dev

**Pull request merged**
